language: python
python:
- '3.5'
install:
- pip install .
script:
- echo "No tests as of now"
deploy:
- provider: releases
  user: deep-compute-ops
  api_key:
    secure: "VHk9G987/p8z3I3QnUHgj50PltCeSeOowY2lcRo5eeVcwKN2H7SRgQAkRygiT7IeZ3JUm27924tDZEJU6MoTBpbHWdsF8InkKCzsdM0dFgY94dXpFOw6lG7KkN6rCGsNbCWZ5tGh3tSkpxgWPq+I8gxrWlKKcaiikrD1Nu0I7GjxUjRfVhgpouCgtRuC6SqMOExzr1aXp2qI2yg7UiLGSIyw1Hnk1cbZ7/ibVhRYjHld02mAlfxdXw9yjPOU3q4NQfst0vsdvVS0KMW36q7fg/NJpHWThpk91w4vW5FeAAwgMsDT2qwsHBVQkwBcxbErQLyHRv8YaYevgpkOdJqFgAE3tS1gRzzw+m7NuiApRg8omc/fovYa40vqBrH4s56YCSAdgvTv9uLFwYTGzMv0mvOymmjJlxNuqelh99L2UlSx32i+klWU7tGI4w9VaBLSpajMiPsharBkCyvkFFs3KfW5uExEvpMki7UKS/tqR7nI1/GzTpffBuPujcKi3W2iuu6oNVR7dR12xZYfvngiapmK7xLtuIiwyvtWxG4Fh3I4KpdNeTMVBkMEcwPgNzowI2cHZW9KkmE5/OhTCrhRJRmyiUNlDAT7Y2M9gF+uLsAUueGFB6Ix9zm/p59ywmGzzyE66zNtGBTBTPd1bTMD8jYcNT2IDsZ98Fd7CRrjyjE="
  file:
    - README.md
    - setup.py
    - LICENSE
    - kwikapi/__init__.py
    - kwikapi/tornado/__init__.py
    - kwikapi/tornado/kwikapi_tornado.py
  name: kwikapi.tornado-0.0.1
  tag_name: 0.0.1
  on:
    repo: deep-compute/kwikapi.tornado
- provider: pypi
  distributions: "sdist bdist_wheel"
  server: https://testpypi.python.org/pypi
  user: deepcompute
  password:
    secure: "I6PEVxs2MO8JQX/IE160jIsOz1Xk65vXpWA0mqM4VGlUrnS+bJMyoI7U8fG1tFoa29LzHb0BLRnDSvWP2mqNm4Ro6lYISZr0PxMZNyCudRif/egZYkRRR54YQ7GgFamqbvGBiaDecbrkmI5yxIpXWPbFr+ctN9nm6vqDDH6N3c7aZSEt90Ddl3Yf4R/EB6w2AkgYwVoGji7cOFnMD1BNTEgbQpNt/DHnnmDdWa2VMuo5InOoyGxA5hUPTK282/6+0XcyI1JMqcSapjo3ZhsGPaUZDHopQqWuEEsXFWJJZm4iTmBsFSGvoQ+Dt+OANzYeB2whukFZYp3eDP79fASeQPJEQEk9WE6Slr7EO/Fc5yBpLFX9UPu/maDKMhZcmaJU95jU6wuU50+8W0QLyIMQwiz480afmFmLWotp0Mu+x8cUi4cF0sI2ZuhZ0fDErahltqk70D2GYCmd1lBTvU5RrY/LQrMNW7D9Oj6JrjWI18zrQfhbdwW57QfgbG81QRVJrPban3r2efwYJzEpP5+u0EarElzXCd2xZhrjSc4v4rM+9XYhjzqX9nfDWQiPzwLmiJR8ruYpKn0420PxswGhPisj4AbaIHA6spJW881hOz7VlKsa8gUB3R9PSK6JQWDyAutwh2U0sPxDs7BQbqChrq7o9sIRWRxPvsPFARUmpA8="
  on:
    tags: false
    branch: master
- provider: pypi
  distributions: "sdist bdist_wheel"
  server: https://upload.pypi.org/legacy/
  user: deepcompute
  password:
    secure: "I6PEVxs2MO8JQX/IE160jIsOz1Xk65vXpWA0mqM4VGlUrnS+bJMyoI7U8fG1tFoa29LzHb0BLRnDSvWP2mqNm4Ro6lYISZr0PxMZNyCudRif/egZYkRRR54YQ7GgFamqbvGBiaDecbrkmI5yxIpXWPbFr+ctN9nm6vqDDH6N3c7aZSEt90Ddl3Yf4R/EB6w2AkgYwVoGji7cOFnMD1BNTEgbQpNt/DHnnmDdWa2VMuo5InOoyGxA5hUPTK282/6+0XcyI1JMqcSapjo3ZhsGPaUZDHopQqWuEEsXFWJJZm4iTmBsFSGvoQ+Dt+OANzYeB2whukFZYp3eDP79fASeQPJEQEk9WE6Slr7EO/Fc5yBpLFX9UPu/maDKMhZcmaJU95jU6wuU50+8W0QLyIMQwiz480afmFmLWotp0Mu+x8cUi4cF0sI2ZuhZ0fDErahltqk70D2GYCmd1lBTvU5RrY/LQrMNW7D9Oj6JrjWI18zrQfhbdwW57QfgbG81QRVJrPban3r2efwYJzEpP5+u0EarElzXCd2xZhrjSc4v4rM+9XYhjzqX9nfDWQiPzwLmiJR8ruYpKn0420PxswGhPisj4AbaIHA6spJW881hOz7VlKsa8gUB3R9PSK6JQWDyAutwh2U0sPxDs7BQbqChrq7o9sIRWRxPvsPFARUmpA8="
  on:
    tags: true
    branch: master
